### ISSUE TITLE
HTC Incredible 4G LTE S-OFF Method

### ISSUE THREAD

**Issue by mdmower** [Rapscallion16/WinDroid_Toolkit#2]
I saw a screenshot of your tool in use on the HTC Incredible 4G LTE (fireball) [here](http://forum.xda-developers.com/droid-incredible-4g/help/unlock-phone-due-to-previous-mods-t3079139/post60045651). It was clear to me that you modified [my original unlock/s-off script](http://forum.xda-developers.com/showthread.php?t=2214653) for your tool, and I [quickly located](https://github.com/WindyCityRockr/WinDroid_Universal_Android_Toolkit/blob/8ab1967ef046187632f98aa141152283cb3b29cd/WinDroid%20Universal%20Android%20Toolkit/MainWindow.xaml.cs#L1607) the fireball specific package [here](https://s.basketbuild.com/dl/devs?dl=WindyCityRockr/WinDroid_Universal_Android_Toolkit/Phones/Droid_Incredible_4G_LTE/FireballUnlock.zip). First and foremost, thanks for retaining my header in the script; that's not so common these days.

But, on to the issue. The script is outdated and misinformed users believe it is still necessary to obtain temp-root with the script before they can achieve S-OFF on fireball. This is not true. Long ago, I helped test a modified rumrunner package from beaups _specifically for this device_. You can find windows and linux versions at [rumrunner.us](http://rumrunner.us/downloads-2/): `rumrunner_fireball.zip` and `rumrunner_fireball.tgz`. These special builds of rumrunner have a temp-root method built into them which works on fireball 2.19.605.2 (the last OTA released for this device). The tool works just fine by itself to achieve S-OFF on a completely stock fireball -- I recommend it.

Let me know if you need more information.

**Comment by mdmower** [comment]
Another thought: users should not apply SuperCID to this device. It kills mobile data on Verizon service. They should retain cid `VZW__001`.  SuperCID was only ever used on this device to allow users to obtain an unlock token from HTCDev. This method of unlock is cumbersome on this device though, since it does not allow flashing the boot partition through recovery. S-OFF really is the better choice.

Also, I host TWRP images for several of the devices you support at [mdmower.cmphys.com](http://mdmower.cmphys.com). Source and commit history is available for all of my releases in case you find something useful.

**Comment by Fiasco1216** [comment]
I should check GitHub more often. I just noticed your post here.

The purpose of including your script wasn't to offer S-OFF but it seemed to be the only way to officially unlock the bootloader at the time. While rumrunner definitely was the better option, I wasn't allowed to include it in the toolkit. Since your script is outdated now, I'll remove it in the next update and point people towards the rumrunner website. That should help the few people who still want to unlock their fireball. Thanks for letting me know and allowing me to use your script for so long.
